version: '3.3'
services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_HOST: 'mongo'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      MONGO_HOST: 'mongo'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
 



