version: '3.3'
services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      MONGO_HOST: 'mongo'
    depends_on:
      - mongo

volumes:
  db-data:
  mongo-config:
 

