version: '2.1'

services:
  file-service:
    image: file-service
    build: .
    environment:
      MONGO_HOST: mongo
    ports:
      - 8080:8080
  mongo:
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-volume:/data/db
volumes:
  mongo-data-volume: