version: '3.3'
services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=password

  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      MONGO_HOST: 'mongo'
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
 

