version: '3.3'
services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_HOST: 'mongodb'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile
    environment:
      MONGO_HOST: 'mongodb'
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
 



