version: '3.7'
services:
  mongodb_service:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  file_service_test:
    build:
        context: .
        dockerfile: test.Dockerfile

volumes:
  mongodb_data_container:
 

